### PR TITLE
Compatiblity with API v6

### LINKED ISSUE #9: 6.1 Update
Good day - Just opening a ticket as an ask if you are planning to update for 6.1? Dalamud updated to API6 and requires that on mods to be allowed to work. 

Thanks!

### PR DESCRIPTION
**Pull request by Pilzinsel64**
Hello! Just wanted to update this plugin. I've added simple compatibility with Dalamaud API level 6.
- Updated DalamudPackager
- Added Punchline in plugin definition
- Removed all context menu codes (hook, settings front-end) to prevent proper crashes

Now I try it with this pull request here. Hope you'll find the time to update the plugin. Otherwise if you want and - of course - you agree @r00telement, I also can publish the update, that wouldn't be a problem. Just need to know in this case. ^^'

Fix #9

### CODE REVIEW

**Comment by tmschorr** [comment]
> Hello! Just wanted to update this plugin. I've added simple compatibility with Dalamaud API level 6.
> 
> * Updated DalamudPackager
> * Added Punchline in plugin definition
> 
> Now I try it with this pull request here. Hope you'll find the time to update the plugin. Otherwise if you want and - of course - you agree, I also can publish the update, that wouldn't be a problem. Just need to know in this case. ^^'
> 
> Fix #9

I would like it, if you could do it.

**Comment by Pilzinsel64** [comment]
> I would like it, if you could do it.

Yes, I really would like to, but I have to wait for the OK of the maintainer... Without I'm not allowed probably. The rules for plugins mentoined in pinned messages in the Goat Place Discord server tellst to wait until the maintainer has the time to update their plugins theirself. Just don't public own builds.

Well, I could try, but I don't want to be the guy that don't respect rules.

If you have any ideas what I could do instead, just throw them out. ;D
One idea from my side is to re-do the whole plugin, give it a new name, and publish it as new plugin. But that would also be bad against the maintainer If he comes back, I guess.

**Comment by r00telement** [comment]
@Pilzinsel64 My apologies for the delay! I'm unfortunately not able to continue maintaining this plugin these days, so to that end, I give you permission to publish updates for PlayerTags to Dalamud from your own fork if you wish to do so! Cheers.

**Comment by r00telement** [comment]
Btw, around the time I quit FF14, Dalamud implemented its own context menu stuff, so you should be able to delete those files in PlayerTags and just use the Dalamud impl.

**Comment by Pilzinsel64** [comment]
Oh, thank you very much for your response @r00telement! And also thank you for your openness and understanding. And don't worry for the delay. You wasn't able to have an idea about that. ❤️

So, that means, the next days I will push the current state to the the offical repo for testing, just to have a working version public. And after that I implement the new context menu.

Btw, I didn't knew that the new context menu is implemented. :D I saw the pull request for the context menu, but I thought it was closed and not merged. Wil check that. ^^

Also, if you ever want to continue working, just notify me and I'll open a new pull request, so you can merge all the work I did.

**Pull request closed without merging**
